class BIN:
    def MODE(self):
        ...
    def MODE_(self):
        ...
    def TRIGger(self):
        ...
    def TYPE(self):
        ...
    def TYPE_(self):
        ...
    def FREQuency(self):
        ...
    def FREQuency_(self):
        ...
    def LEVel(self):
        ...
    def LEVeL_(self):
        ...
    def SPEED(self):
        ...
    def SPEED_(self):
        ...
    def RANGE(self):
        ...
    def RANGE_(self):
        ...
    def EQU_CCT(self):
        ...
    def EQU_CCT_(self):
        ...
    def FUNC1(self):
        ...
    def FUNC1_(self):
        ...
    def FUNC2(self):
        ...
    def FUNC2_(self):
        ...
    def BIAS(self):
        ...
    def BIAS_STAT_(self):
        ...
    def LIMit1(self):
        ...
    def LIMit1_(self):
        ...
    def LIMit2(self):
        ...
    def LIMit2_(self):
        ...
    def NOMinal1(self):
        ...
    def NOMinal1_(self):
        ...
    def NOMinal2(self):
        ...
    def NOMinal2_(self):
        ...
    def HI_LIMit1(self):
        ...
    def HI_LIMit1_(self):
        ...
    def HI_LIMit2(self):
        ...
    def HI_LIMit2_(self):
        ...
    def LO_LIMit1(self):
        ...
    def LO_LIMit1_(self):
        ...
    def LO_LIMit2(self):
        ...
    def LO_LIMit2_(self):
        ...
    def MAX_LIMit(self):
        ...
    def MAX_LIMit_(self):
        ...
    def MIN_LIMit(self):
        ...
    def MIN_LIMit_(self):
        ...
    def DEL_LAST(self):
        ...
    def DEL_ALL(self):
        ...
    def BIN0_COUNT_(self):
        ...
    def BIN1_COUNT_(self):
        ...
    def BIN2_COUNT_(self):
        ...
    def BIN3_COUNT_(self):
        ...
    def BIN4_COUNT_(self):
        ...
    def BIN5_COUNT_(self):
        ...
    def BIN6_COUNT_(self):
        ...
    def BIN7_COUNT_(self):
        ...
    def BIN8_COUNT_(self):
        ...
    def BIN9_COUNT_(self):
        ...
    def TOTALS_(self):
        ...