class bit:
    def bitand(self):
        ...
    def bitor(self):
        ...
    def bitxor(self):
        ...
    def clear(self):
        ...
    def get(self):
        ...
    def getfiled(self):
        ...
    def set(self):
        ...
    def setfield(self):
        ...
    def test(self):
        ...
    def toggle(self):
        ...