class bufferVar:
    def appendmode(self):
        ...
    def basetimestamp(self):
        ...
    def cachemode(self):
        ...
    def capacity(self):
        ...
    def clear(self):
        ...
    def clearcache(self):
        ...
    def collectsourcevalues(self):
        ...
    def collecttimestamps(self):
        ...
    def fillcount(self):
        ...
    def fillmode(self):
        ...
    def measurefunctions(self):
        ...
    def n(self):
        ...
    def readings(self):
        ...
    def sourcefunctions(self):
        ...
    def sourceoutputstates(self):
        ...
    def sourceranges(self):
        ...
    def sourcecalues(self):
        ...
    def statuses(self):
        ...
    def timestampresolution(self):
        ...
    def timestamps(self):
        ...