class digio:
    def readbit(self):
        ...
    def readport(self):
        ...
    def trigger_assert(self):
        ...
    def trigger_clear(self):
        ...
    def trigger_EVENT_ID(self):
        ...
    def trigger_mode(self):
        ...
    def trigger_overrun(self):
        ...
    def trigger_pulsewidth(self):
        ...
    def trigger_release(self):
        ...
    def trigger_reset(self):
        ...
    def trigger_stimulus(self):
        ...
    def trigger_wait(self):
        ...
    def writebit(self):
        ...
    def writeport(self):
        ...
    def writeprotect(self):
        ...