class display:
    def clear(self):
        ...
    def getannunciators(self):
        ...
    def getcursor(self):
        ...
    def getlastkey(self):
        ...
    def gettext(self):
        ...
    def inputvalue(self):
        ...
    def loadmenu_add(self):
        ...
    def loadmenu_catalog(self):
        ...
    def loadmenu_delete(self):
        ...
    def locallockout(self):
        ...
    def menu(self):
        ...
    def numpad(self):
        ...
    def prompt(self):
        ...
    def screen(self):
        ...
    def sendkey(self):
        ...
    def setcursor(self):
        ...
    def settext(self):
        ...
    def smu_digits(self):
        ...
    def smu_limit_func(self):
        ...
    def smu_measure_func(self):
        ...
    def trigger_clear(self):
        ...
    def trigger_EVENT_ID(self):
        ...
    def trigger_overrun(self):
        ...
    def trigger_wait(self):
        ...
    def waitkey(self):
        ...