class eventlog:
    def all(self):
        ...
    def clear(self):
        ...
    def count(self):
        ...
    def enable(self):
        ...
    def next(self):
        ...
    def overwritemethod(self):
        ...