class fs:
    def chdir(self):
        ...
    def cwd(self):
        ...
    def is_dir(self):
        ...
    def is_file(self):
        ...
    def mkdir(self):
        ...
    def readdir(self):
        ...
    def rmdir(self):
        ...