class io:
    def close(self):
        ...
    def flush(self):
        ...
    def input(self):
        ...
    def open(self):
        ...
    def read(self):
        ...
    def type(self):
        ...
    def write(self):
        ...
