class lan:
    def applysettings(self):
        ...
    def autoconnect(self):
        ...
    def config_dns_address(self):
        ...
    def config_dns_domain(self):
        ...
    def config_dns_dynamic(self):
        ...
    def config_dns_hostname(self):
        ...
    def config_dns_verify(self):
        ...
    def config_duplex(self):
        ...
    def config_gateway(self):
        ...
    def config_ipaddress(self):
        ...
    def config_method(self):
        ...
    def config_speed(self):
        ...
    def config_subnetmask(self):
        ...
    def linktimeout(self):
        ...
    def lxidomain(self):
        ...
    def nagle(self):
        ...
    def reset(self):
        ...
    def restoredefaults(self):
        ...
    def status_dns_address(self):
        ...
    def status_dns_name(self):
        ...
    def status_duplex(self):
        ...
    def status_gateway(self):
        ...
    def status_ipaddress(self):
        ...
    def status_macaddress(self):
        ...
    def status_port_dst(self):
        ...
    def status_port_rawsocket(self):
        ...
    def status_port_telnet(self):
        ...
    def status_port_vxi11(self):
        ...
    def status_speed(self):
        ...
    def status_subnetmask(self):
        ...
    def timewait(self):
        ...
    def trigger_assert(self):
        ...
    def trigger_clear(self):
        ...
    def trigger_connect(self):
        ...
    def trigger_connected(self):
        ...
    def trigger_disconnect(self):
        ...
    def trigger_EVENT_ID(self):
        ...
    def trigger_ipaddress(self):
        ...
    def trigger_mode(self):
        ...
    def trigger_overrun(self):
        ...
    def trigger_protocol(self):
        ...
    def trigger_pseudostate(self):
        ...
    def trigger_stimulus(self):
        ...
    def trigger_wait(self):
        ...