class localnode:
    def autolinefreq(self):
        ...
    def description(self):
        ...
    def license(self):
        ...
    def linefreq(self):
        ...
    def model(self):
        ...
    def ...word(self):
        ...
    def ...wordmode(self):
        ...
    def prompts(self):
        ...
    def prompts4882(self):
        ...
    def reset(self):
        ...
    def revision(self):
        ...
    def serialno(self):
        ...
    def showerrors(self):
        ...