from requests import delete


class script:
    def anonymous(self):
        ...
    def delete(self):
        ...
    def factory_catalog(self):
        ...
    def load(self):
        ...
    def new(self):
        ...
    def newautorun(self):
        ...
    def restore(self):
        ...
    def run(self):
        ...
    def user_catalog(self):
        ...