class scriptVar:
    def autorun(self):
        ...
    def list(self):
        ...
    def name(self):
        ...
    def run(self):
        ...
    def save(self):
        ...
    def source(self):
        ...