class status:
    def condition(self):
        ...
    def measurement_(self):
        ...
    def measurement_buffer_available_(self):
        ...
    def measurement_current_limit_(self):
        ...
    def measurement_instrument_(self):
        ...
    def measurement_instrument_smu_(self):
        ...
    def measurement_reading_overflow_(self):
        ...
    def measurement_voltage_limit_(self):
        ...
    def node_enable(self):
        ...
    def node_event(self):
        ...
    def operation_(self):
        ...
    def operation_calibrating_(self):
        ...
    def operation_instrument_(self):
        ...
    def operation_instrument_digio_(self):
        ...
    def operation_instrument_digio_trigger_overrun_(self):
        ...
    def operation_instrument_lan(self):
        ...
    def operation_instrument_lan_trigger_overrun_(self):
        ...
    def operation_instrument_smu_(self):
        ...
    def operation_instrument_smu_trigger_overrun(self):
        ...
    def operation_instrument_trigger_blender_(self):
        ...
    def operation_instrument_trigger_blender_tirgger_overrun_(self):
        ...
    def operation_instrument_trigger_timer_(self):
        ...
    def operation_instrument_trigger_timer_trigger_overrun_(self):
        ...
    def operation_instrument_tsplink_(self):
        ...
    def operation_instrument_tsplink_trigger_overrun_(self):
        ...
    def operation_measuring_(self):
        ...
    def operation_remote_(self):
        ...
    def operation_sweeping_(self):
        ...
    def operation_trigger_overrun_(self):
        ...
    def operation_user_(self):
        ...
    def questionable_(self):
        ...
    def questionable_calibration_(self):
        ...
    def questionable_instrument_(self):
        ...
    def questionable_instrument_smu_(self):
        ...
    def questionable_over_temperature_(self):
        ...
    def questionable_unstable_output_(self):
        ...
    def request_enable(self):
        ...
    def request_event(self):
        ...
    def reset(self):
        ...
    def standard_(self):
        ...
    def system_(self):
        ...
    def system2_(self):
        ...
    def system3_(self):
        ...
    def system4_(self):
        ...
    def system5_(self):
        ...