class trigger:
    def blender_clear(self):
        ...
    def blender_EVENT_ID(self):
        ...
    def blender_orenable(self):
        ...
    def blender_overrun(self):
        ...
    def blender_reset(self):
        ...
    def blender_stimulus(self):
        ...
    def blender_wait(self):
        ...
    def clear(self):
        ...
    def EVENT_ID(self):
        ...
    def generator_assert(self):
        ...
    def generator_EVENT_ID(self):
        ...
    def timer_clear(self):
        ...
    def timer_count(self):
        ...
    def timer_delay(self):
        ...
    def timer_delaylist(self):
        ...
    def timer_EVENT_ID(self):
        ...
    def timer_overrun(self):
        ...
    def timer_...through(self):
        ...
    def timer_reset(self):
        ...
    def timer_stimulus(self):
        ...
    def timer_wait(self):
        ...
    def wait(self):
        ...