class tspnet:
    def clear(self):
        ...
    def connect(self):
        ...
    def disconnect(self):
        ...
    def execute(self):
        ...
    def idn(self):
        ...
    def read(self):
        ...
    def readavailable(self):
        ...
    def reset(self):
        ...
    def termination(self):
        ...
    def timeout(self):
        ...
    def tsp_abort(self):
        ...
    def tsp_abortonconnect(self):
        ...
    def tsp_rbtablecopy(self):
        ...
    def tsp_runscript(self):
        ...
    def wirte(self):
        ...